export const JSON_URL = 'https://www.cbr-xml-daily.ru/daily_json.js'
export const DATETIME_FORMAT = 'MMM DD YYYY, HH:mm Z'
export const CURRENCY_CONVERTER_LIMIT = 6
export const DEFAULT_CONVERTER_AMOUNT = 1
export const DEFAULT_CONVERTER_FROM_CURRENCY = 'USD'
export const DEFAULT_CONVERTER_TO_CURRENCY = 'EUR'
export const CURRENCY_DIFFERENCE_LIMIT = 3
export const MULTIPLICATION = '*'
export const DIVISION = '/'
